# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trackers', '0002_auto_20160324_0525'),
        ('events', '0002_auto_20160324_0525'),
        ('pilots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPilot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeatEvent',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.PositiveSmallIntegerField(choices=[(0, 'Gate Trigger'), (1, 'Area Entered Trigger'), (2, 'Area Exit Trigger'), (3, 'Crash Trigger'), (4, 'Land Trigger'), (5, 'Takeoff Trigger'), (6, 'Arm Trigger'), (7, 'Disarm Trigger'), (8, 'Start Trigger'), (9, 'End Trigger')], verbose_name='trigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Race Name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RaceGroup',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Heat number')),
                ('pilots', models.ManyToManyField(through='races.GroupPilot', to='pilots.Pilot')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='races.Race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceHeat',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Heat number')),
                ('active', models.BooleanField(default=False)),
                ('goal_start_time', models.DateTimeField(verbose_name='Heat goal start time')),
                ('goal_end_time', models.DateTimeField(verbose_name='Heat goal end time')),
                ('started_time', models.DateTimeField(blank=True, null=True, verbose_name='Heat started time')),
                ('ended_time', models.DateTimeField(blank=True, null=True, verbose_name='Heat ended time')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='races.RaceGroup')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='races.Race')),
            ],
        ),
        migrations.AddField(
            model_name='heatevent',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_events', to='races.RaceHeat'),
        ),
        migrations.AddField(
            model_name='heatevent',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_events', to='trackers.Tracker'),
        ),
        migrations.AddField(
            model_name='grouppilot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.RaceGroup'),
        ),
        migrations.AddField(
            model_name='grouppilot',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilots.Pilot'),
        ),
        migrations.AddField(
            model_name='grouppilot',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.Tracker'),
        ),
        migrations.AlterUniqueTogether(
            name='raceheat',
            unique_together=set([('number', 'race')]),
        ),
        migrations.AlterUniqueTogether(
            name='racegroup',
            unique_together=set([('number', 'race')]),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=set([('name', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='grouppilot',
            unique_together=set([('pilot', 'group')]),
        ),
    ]
