# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 05:23
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20160510_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceheat',
            name='active',
        ),
        migrations.AddField(
            model_name='raceheat',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Restarting'), (3, 'Ended')], default=0),
        ),
    ]
