# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20160515_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='current_heat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_of', to='races.RaceHeat'),
        ),
    ]
