# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTimer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='slug')),
                ('duration', models.DurationField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical timer',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='slug')),
                ('duration', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicaleventtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaleventtemplate',
            name='title',
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleventtemplate',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='historicaleventtemplate',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='timer',
            name='tempalte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventTemplate'),
        ),
        migrations.AddField(
            model_name='historicaltimer',
            name='tempalte',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.EventTemplate'),
        ),
    ]
