# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='tracker_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unkown'), (0, 'iLap')], default=0),
        ),
    ]
